/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateUserSettings {
  preferredLanguage: string
  familyName: string
  givenName: string
  phoneNumber: string
  email: string
}
