/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AddTradingSymbol {
  name: string
  productType: string
  baseCurrencyId: string
  quoteCurrencyId: string
  minQuantity: number
  minPrice: number
  feeProportion: number
}
