/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetInvestors {
  offset: number
  limit: number
  idCardOrPassport?: string
  customerCode?: string
  customerName?: string
  customerType?: string
  riskLevel?: string
  verificationLevel?: string
  accountOpenDateBegin?: number
  accountOpenDateEnd?: number
  registeredBank?: string
  emailAddress?: string
  publicId?: string
  isOnboard?: boolean
  isRejected?: boolean
  isClosed?: boolean
}
