/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetUsers {
  offset: number
  limit: number
  username?: string
  familyNameKw?: string
  givenNameKw?: string
  nameEnglishKw?: string
  emailKw?: string
  emailVerified?: boolean
  phoneVerified?: boolean
  isBlocked?: boolean
  ageMin?: number
  ageMax?: number
  registrationDateMin?: number
  registrationDateMax?: number
}
