/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateSecReportBusinessWallet {
  tableId: number
  headers: [
    'intermediary_id',
    'report_date',
    'is_update',
    'is_wallet_for_customer',
    'wallet_for_customer_is_smart_contract',
    'wallet_for_customer_smart_contract_address',
    'wallet_for_customer_wallet_type',
    'wallet_for_customer_wallet_flag',
    'wallet_for_customer_wallet_flag_detail',
    'wallet_for_customer_creation_date',
    'wallet_for_customer_wallet_address',
    'wallet_for_customer_asset_id',
    'wallet_for_customer_asset_isin',
    'wallet_for_customer_asset_short_name',
    'wallet_for_business_wallet_flag',
    'wallet_for_business_wallet_flag_detail',
    'wallet_for_business_creation_date',
    'wallet_for_business_wallet_address',
    'wallet_for_business_asset_id',
    'wallet_for_business_asset_short_name',
  ]
  body: [
    number,
    number,
    boolean,
    boolean,
    boolean,
    string,
    string,
    boolean,
    string,
    number,
    string,
    string,
    string,
    string,
    string,
    string,
    number,
    string,
    string,
    string,
  ][]
}
