/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateSecReportCustomerData {
  tableId: number
  headers: [
    'intermediary_id',
    'report_date',
    'is_update',
    'customer_code',
    'customer_code_amlo',
    'opening_account_date',
    'customer_id',
    'customer_type',
    'tax_id',
    'name_title',
    'first_name',
    'last_name',
    'middle_name',
    'is_thai_nationality',
    'nationality',
    'country',
    'birth_yy',
    'contact_email_address',
    'bank_short_name',
    'bank_branch_code',
    'bank_account_number',
  ]
  body: [
    number,
    number,
    boolean,
    string,
    string,
    number,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    boolean,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ][]
}
