/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateSecReportDtwReport {
  tableId: number
  headers: [
    'intermediary_id',
    'report_date',
    'customer_type',
    'customer_code',
    'customer_code_amlo',
    'customer_country',
    'customer_wallet_address',
    'customer_wallet_issuer',
    'is_digital_asset',
    'transaction_date',
    'transaction_time',
    'transaction_no',
    'asset_isin',
    'asset_id',
    'asset_short_name',
    'transaction_purpose',
    'transaction_purpose_detail',
    'quantity',
    'fee',
    'fee_thb',
    'destination_identity_type',
    'destination_country',
    'destination_wallet_address',
    'destination_bank_code',
    'destination_bank_short_name',
    'destination_bank_account_no',
  ]
  body: [
    number,
    number,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    number,
    number,
    string,
    string,
    number,
    string,
    string,
    string,
    number,
    number,
    number,
    string,
    string,
    string,
    string,
    string,
    string,
  ][]
}
